# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - Rag-Gemini-LLM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .streamlit/secrets.toml file
        run: |
          mkdir -p .streamlit
          cat <<EOF > .streamlit/secrets.toml
          AZURE_CONNECTION_STRING = "${{ secrets.AZURE_CONNECTION_STRING }}"
          AZURE_CONTAINER_NAME = "${{ secrets.AZURE_CONTAINER_NAME }}"
          GOOGLE_API_KEY = "${{ secrets.GOOGLE_API_KEY }}"
          PINECONE_API_KEY = "${{ secrets.PINECONE_API_KEY }}"
          PINECONE_ENVIRONMENT = "${{ secrets.PINECONE_ENVIRONMENT }}"
          PINECONE_INDEX1 = "${{ secrets.PINECONE_INDEX1 }}"
          EOF

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Rag-Gemini-LLM'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_62B02B1EDB8A49E488C98FDF85315ED1 }}
